name: flutter_case_umitmutluu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #NETWORK
  dio: ^5.3.0

  #UTILITIES
  pretty_dio_logger: ^1.3.1
  path_provider: ^2.1.1
  path: 1.8.3

  #CACHING
  cached_network_image: ^3.3.0

  #PARSING
  json_annotation: ^4.8.1

  #UI TOOLS
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0

  #STORAGE
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0

  #LOCALİZATİON
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  #STATE MANAGEMENT
  get_it: ^7.6.4
  auto_route: ^7.7.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  pitch_detector_dart: ^0.0.1
  permission_handler: ^11.1.0
  phosphor_flutter: ^2.0.1
#  painter: ^2.0.0
  flutter_painter_v2: ^2.0.1
  image_gallery_saver: ^2.0.3
  image_editor_plus:
    path : ../image_editor_plus
#  image_editor: ^1.3.0
#  erase_restore: ^0.0.1
  image_picker: ^1.0.4
  extended_image: ^8.0.2
  oktoast: ^3.1.5
  image_size_getter: ^2.1.2

dev_dependencies:
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  bloc_test: ^9.1.5
  mockito: ^5.4.3
  sqflite_common_ffi: ^2.3.1
  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints:

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 400
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 300
          style: italic